### ISSUE TITLE
There are no new images since Publisher workflow has failed on Feb 6, 2023

### ISSUE THREAD

**Issue by vadimofd** [worksome/rover#9]

**Comment by owenvoke** [comment]
Hey @vadimofd, apologies for not seeing this. We haven't been keeping an eye on this project.

I'll work on sorting this out on Monday, and try to keep on top of this.

**Comment by vadimofd** [comment]
Thank you very much!

**Comment by owenvoke** [comment]
@vadimofd, I have released a new version for [0.19.1](https://hub.docker.com/layers/worksome/rover/0.19.1/images/sha256-184d626ceee909bdbefca98e36d985416ce5233400714789571c5d57caa2b80a?context=explore). 👍🏻

It looks like the workflow was disabled as it hadn't run in 3 months. However, I don't quite understand why it wasn't running daily (which it should with the `cron`). 🤔
